language: php
sudo: required
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        - $HOME/.php-cs-fixer

env:
    global:
        - TEST_COMMAND="composer test"
        - COMPOSER_FLAGS="--prefer-dist"
        - SYMFONY_PHPUNIT_VERSION=6.5

jobs:
  include:
    - php: 7.2
      before_install:
        - mkdir -p "$HOME/.php-cs-fixer"
        - composer require friendsofphp/php-cs-fixer
      script:
        - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
    - php: 7.2
      services:
        - docker
      before_install:
        - docker build -t buzz/tests .
        - docker run -d -p 127.0.0.1:8080:80 -p 127.0.0.1:3128:3128 buzz/tests
        - docker ps -a
      before_script:
        - ./vendor/bin/http_test_server > /dev/null 2>&1 &
      script:
        - ./vendor/bin/phpunit --testsuite Integration

      # Test with lowest dependencies
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

      # Test the latest stable release
    - php: 7.2
      env: COVERAGE=true TEST_COMMAND="composer test-ci"
    - php: 7.3

      # Force some major versions of Symfony
    - php: 7.2
      env: DEPENDENCIES="dunglas/symfony-lock:^3"
    - php: 7.2
      env: DEPENDENCIES="dunglas/symfony-lock:^4"

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.xml; fi
